### ISSUE TITLE
Ready for alpha use?

### ISSUE THREAD

**Issue by expez** [juxt/cylon#30]
This looks positively fantastic, but is it ready for use outside the juxt consultancy?  I notice  the readme states that this isn't production ready until marked 1.0, is that likely to happen in 2015?  

If the answer is in the affirmative, would it be possible to write some documentation as to how cylon can be put to use?  I'd like to use it for a REST service, written with liberator, if you're wondering about which section to write first :)

**Comment by michaelklishin** [comment]
It is used outside of Juxt, although before the docs are in place, I would not claim it is 1.0 quality. Feel free to give it a try.

**Comment by malcolmsparks** [comment]
It is definitely my intention to provide more documentation now that the library has stabilized. @tangrammer is doing quite a bit of work on providing examples and documentation, and I'm planning to help by generating templates the demonstrate various cylon use-cases.

**Comment by expez** [comment]
Great! 

Consider adding some documentation for `modular` too.  You're likely to get more users--and more contributors--if people don't have to read the code to figure out what's on offer.  I think you know this, but lack for time, as the Bidi docs are quite good.
